"""Create initial tables

Revision ID: 0d5f57d07c67
Revises:
Create Date: 2026-04-02 20:07:10.354619

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d5f57d07c67"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "villager_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("started_on", sa.DateTime(), nullable=False),
        sa.Column("finished_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "villager_snapshot_villagers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column(
            "species",
            sa.Enum(
                "ALLIGATOR",
                "ANTEATER",
                "BEAR",
                "BEAR_CUB",
                "BIRD",
                "BULL",
                "CAT",
                "CHICKEN",
                "COW",
                "DEER",
                "DOG",
                "DUCK",
                "EAGLE",
                "ELEPHANT",
                "FROG",
                "GOAT",
                "GORILLA",
                "HAMSTER",
                "HIPPO",
                "HORSE",
                "KANGAROO",
                "KOALA",
                "LION",
                "MONKEY",
                "MOUSE",
                "OCTOPUS",
                "OSTRICH",
                "PENGUIN",
                "PIG",
                "RABBIT",
                "RHINOCEROS",
                "SHEEP",
                "SQUIRREL",
                "TIGER",
                "WOLF",
                name="villagerspecies",
            ),
            nullable=False,
        ),
        sa.Column("checksum", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["villager_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id", "snapshot_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("villager_snapshot_villagers")
    op.drop_table("villager_snapshots")
    # ### end Alembic commands ###
