"""Create initial tables

Revision ID: 244e5af74928
Revises:
Create Date: 2026-03-30 19:24:35.857404

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "244e5af74928"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "villager_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("started_on", sa.DateTime(), nullable=False),
        sa.Column("finished_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "villager_snapshot_villagers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("checksum", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["villager_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id", "snapshot_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("villager_snapshot_villagers")
    op.drop_table("villager_snapshots")
    # ### end Alembic commands ###
