"""Add diff tables

Revision ID: 4d50f0fce23a
Revises: 0d5f57d07c67
Create Date: 2026-04-05 14:32:35.859331

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d50f0fce23a"
down_revision: Union[str, Sequence[str], None] = "0d5f57d07c67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "villager_snapshot_activations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.Uuid(), nullable=True),
        sa.Column("target", sa.Uuid(), nullable=False),
        sa.Column("started_on", sa.DateTime(), nullable=False),
        sa.Column("finished_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source"],
            ["villager_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target"],
            ["villager_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "villager_snapshot_diff",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.Uuid(), nullable=True),
        sa.Column("target", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source"],
            ["villager_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target"],
            ["villager_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "target"),
    )
    op.create_table(
        "villager_snapshot_diff_items",
        sa.Column("diff_id", sa.Uuid(), nullable=False),
        sa.Column("villager_id", sa.String(length=64), nullable=False),
        sa.Column(
            "change",
            sa.Enum("ADDED", "UPDATED", "DELETED", name="diffchange"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["diff_id"],
            ["villager_snapshot_diff.id"],
        ),
        sa.PrimaryKeyConstraint("diff_id", "villager_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("villager_snapshot_diff_items")
    op.drop_table("villager_snapshot_diff")
    op.drop_table("villager_snapshot_activations")
    # ### end Alembic commands ###
