include:
  - docker-compose.logging.yaml
  - docker-compose.kafka.yaml
  - docker-compose.mariadb.yaml

services:
  import-event-orchestrator:
    build:
      context: .
      dockerfile: import_event_orchestrator.dockerfile
    image: import-event-orchestrator:latest
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: ac_user
      DB_PASSWORD_FILE: /run/secrets/db_user_password
      DB_DATABASE: animal_crossing
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      TELEMETRY_ENABLED: "false"
      TELEMETRY_EXPORTER_ENDPOINT: "http://otel-collector:4317"
    develop:
      watch:
        - action: rebuild
          path: src/import_event_orchestrator
        - action: rebuild
          path: src/messaging
        - action: rebuild
          path: pyproject.toml
    depends_on:
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
    secrets:
      - db_user_password

  import-worker:
    build:
      context: .
      dockerfile: import_worker.dockerfile
    image: import-worker:latest
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: ac_user
      DB_PASSWORD_FILE: /run/secrets/db_user_password
      DB_DATABASE: animal_crossing
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      # TELEMETRY_ENABLED: "false"
      # TELEMETRY_EXPORTER_ENDPOINT: "http://otel-collector:4317"
    develop:
      watch:
        - action: rebuild
          path: src/import_worker
        - action: rebuild
          path: src/messaging
        - action: rebuild
          path: pyproject.toml
    depends_on:
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
    secrets:
      - db_user_password
